# Generated by Django 5.1.6 on 2026-04-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_subcategoria_producto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
